// 1.5: тёмная тема (панель форматирования), узкий экран (домашка, папки, поиск), анимация вкладок темы/правила.
import { _electron as electron } from 'playwright';
import fs from 'fs';
const OUT = process.env.OUT;
const dir = '/tmp/mnema15b';
fs.rmSync(dir, { recursive: true, force: true });
const app = await electron.launch({ executablePath: process.cwd() + '/node_modules/electron/dist/electron', args: [process.cwd() + '', '--no-sandbox'], env: { ...process.env, MNEMA_USER_DATA: dir } });
const win = await app.firstWindow();
const errors = [];
win.on('pageerror', (e) => errors.push(e.message));
win.on('console', (m) => m.type() === 'error' && errors.push('console: ' + m.text()));
const step = (s) => console.log('•', s);
const shot = async (n) => { await win.waitForTimeout(350); await win.screenshot({ path: `${OUT}/${n}.png` }); };
await win.getByRole('button', { name: 'Пропустить' }).click({ timeout: 2500 }).catch(() => {}); // знакомство при первом запуске
await win.getByRole('button', { name: 'Посмотреть на примере' }).click();
await win.waitForTimeout(400);
await win.keyboard.press('Control+p');
await win.locator('.palette input').fill('>тёмная');
await win.keyboard.press('Enter');
await win.waitForTimeout(500);
await win.locator('.tree-row.subject', { hasText: 'Физика' }).locator('.twisty').click();
await win.locator('.tree-row', { hasText: 'Закон Ома' }).locator('.tree-label').click();
await win.waitForTimeout(800);
await win.locator('.ProseMirror p').first().click({ clickCount: 3 });
await win.waitForTimeout(400);
step('dark bubble bg=' + (await win.locator('.bubble').evaluate((e) => getComputedStyle(e).backgroundColor)));
await shot('h1-dark-bubble');
// Предмет без тем: пусто под вкладками
await win.locator('.tree-row.subject', { hasText: 'История' }).locator('.tree-label').click();
await win.waitForTimeout(400);
await win.getByRole('tab', { name: /Правила/ }).click().catch(() => step('нет вкладки Правила'));
await win.waitForTimeout(100);
step('pane anim: ' + (await win.locator('.tab-pane').first().evaluate((e) => getComputedStyle(e).animationName)));
await shot('h2-rules');
// Узкий экран
await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].setSize(400, 820));
await win.waitForTimeout(600);
await win.getByRole('button', { name: 'Сегодня' }).first().click().catch(() => {});
await win.waitForTimeout(400);
await shot('h3-mobile-today');
await win.locator('.hw-today').getByRole('button', { name: /Записать/ }).click();
await win.waitForTimeout(400);
await shot('h4-mobile-hwform');
const overflow = await win.evaluate(() => document.documentElement.scrollWidth - document.documentElement.clientWidth);
step('horizontal overflow: ' + overflow);
await win.keyboard.press('Escape');
await win.waitForTimeout(300);
await win.locator('.mobile-bar button[aria-label="Поиск"]').click().catch(() => step('нет кнопки поиска в мобильной панели'));
await win.locator('.palette input').fill('клетк');
await win.waitForTimeout(300);
await shot('h5-mobile-search');
console.log('errors', JSON.stringify(errors));
await app.close();
