import { _electron as electron } from 'playwright';
import fs from 'fs';
const EXE = process.cwd() + '/node_modules/electron/dist/electron';
const app = await electron.launch({ executablePath: EXE, args: [process.cwd() + '', '--no-sandbox'] });
const userData = await app.evaluate(({ app }) => app.getPath('userData'));
await app.evaluate(({ dialog }, dir) => { dialog.showOpenDialog = async () => ({ canceled: false, filePaths: [dir] }); }, '/tmp/mnema-vault');
const win = await app.firstWindow();
const errors = [];
win.on('pageerror', (e) => errors.push(e.message));
await win.getByRole('button', { name: 'Пропустить' }).click({ timeout: 2500 }).catch(() => {}); // знакомство при первом запуске
await win.getByRole('button', { name: 'Посмотреть на примере' }).click();
await win.getByRole('button', { name: 'Возможности' }).click();
await win.getByRole('switch', { name: 'Obsidian' }).click();
await win.locator('.tree-item', { hasText: 'Биология' }).click();
await win.getByRole('button', { name: 'Действия с предметом' }).click();
await win.getByRole('menuitem', { name: /Obsidian/ }).click();
await win.getByRole('button', { name: 'Выбрать папку…' }).click();
await win.getByText('Митоз').waitFor();
await win.screenshot({ path: process.env.OUT + '/e1-obsidian.png' });
await win.locator('.file-item', { hasText: 'Митоз' }).locator('input').check();
await win.getByRole('button', { name: /Импортировать/ }).click();
await win.locator('.topic-row', { hasText: 'Митоз' }).click();
await win.waitForTimeout(1200); console.log('NOTE', (await win.evaluate(() => document.querySelector('.note-doc')?.innerHTML ?? 'none')).slice(0, 600));
await win.waitForTimeout(500);
await win.screenshot({ path: process.env.OUT + '/e2-imported.png' });
await app.close();
const d = JSON.parse(fs.readFileSync(userData + '/mnema-data.json', 'utf8'));
const t = d.topics.find((x) => x.name === 'Митоз');
console.log('subject ok:', d.subjects.find((s) => s.id === t.subjectId).name);
console.log('note:', t.note.replace(/data:image\/png;base64,[A-Za-z0-9+/=]+/, 'DATA').replace(/\n/g, '⏎'));
console.log('errors', JSON.stringify(errors));
fs.rmSync(userData, { recursive: true, force: true });
