import { _electron as electron } from 'playwright';
import fs from 'fs';
const OUT = 'fold'; fs.mkdirSync(OUT, { recursive: true });
const dir = '/tmp/mnemaF'; fs.rmSync(dir, { recursive: true, force: true });
const app = await electron.launch({ executablePath: process.cwd() + '/node_modules/electron/dist/electron', args: [process.cwd() + '', '--no-sandbox'], env: { ...process.env, MNEMA_USER_DATA: dir } });
const win = await app.firstWindow();
const errors = []; win.on('pageerror', (e) => errors.push(e.message));
const shot = async (n) => { await win.waitForTimeout(400); await win.screenshot({ path: `${OUT}/${n}.png` }); };
await win.getByRole('button', { name: 'Пропустить' }).click({ timeout: 2500 }).catch(() => {}); // знакомство при первом запуске
await win.getByRole('button', { name: 'Посмотреть на примере' }).click();
await win.locator('.sidebar .create-btn').click();
await win.locator('.modal .create-item', { hasText: 'Новая папка' }).click();
await win.waitForTimeout(300);
await shot('f1-newfolder');
await win.locator('.modal').getByLabel('Название').fill('Математика');
await win.locator('.modal').getByRole('button', { name: 'Создать' }).click();
await win.waitForTimeout(300);
await win.locator('.sidebar .create-btn').click();
await win.locator('.modal .create-item', { hasText: 'Новый предмет' }).click();
await win.waitForTimeout(300);
await win.locator('.modal .icon-pick-btn').click();
await shot('f2-newsubject');
await win.locator('.modal .icon-pop .ico-opt').nth(3).click();
await win.locator('.modal').getByLabel('Название').fill('Алгебра');
const sel = win.locator('.modal select'); if (await sel.count()) await sel.selectOption({ index: 1 });
await win.locator('.modal').getByRole('button', { name: 'Создать' }).click();
await win.waitForTimeout(400);
await win.locator('.tree-row.folder .tree-label').first().click();
await shot('f3-folder');
console.log('errors', JSON.stringify(errors));
await app.close();
