import { chromium } from 'playwright';
const OUT = process.env.OUT;
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' });
const page = await browser.newPage({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2, isMobile: true, hasTouch: true });
const errors = [];
page.on('pageerror', (e) => errors.push(e.message));
await page.goto('http://localhost:4174');
await page.evaluate(() => localStorage.clear());
await page.reload();
await page.screenshot({ path: OUT + '/m0-welcome.png' });
await page.getByRole('button', { name: 'Посмотреть на примере' }).click();
await page.waitForTimeout(400);
await page.screenshot({ path: OUT + '/m1-today.png' });
await page.getByRole('button', { name: 'Меню' }).click();
await page.waitForTimeout(400);
await page.screenshot({ path: OUT + '/m2-drawer.png' });
await page.locator('.tree-row.subject', { hasText: 'Физика' }).locator('.twisty').click();
await page.locator('.tree-row', { hasText: 'Закон Ома' }).locator('.tree-label').click();
await page.waitForTimeout(500);
await page.screenshot({ path: OUT + '/m3-topic.png' });
await page.getByRole('button', { name: /Учить/ }).first().click();
await page.waitForTimeout(400);
await page.getByRole('button', { name: 'Показать ответ' }).click();
await page.waitForTimeout(300);
await page.screenshot({ path: OUT + '/m4-review.png' });
await page.getByRole('button', { name: 'Закончить' }).click().catch(() => page.keyboard.press('Escape'));
await page.waitForTimeout(300);
await page.getByRole('button', { name: 'Меню' }).click();
await page.getByRole('button', { name: 'Настройки', exact: true }).click();
await page.waitForTimeout(400);
await page.screenshot({ path: OUT + '/m5-settings.png' });
await page.getByRole('button', { name: 'Меню' }).click();
await page.getByRole('button', { name: 'Статистика' }).click();
await page.waitForTimeout(400);
await page.screenshot({ path: OUT + '/m6-stats.png' });
// Модалка карточки
await page.getByRole('button', { name: 'Меню' }).click();
await page.locator('.tree-row', { hasText: 'Закон Ома' }).locator('.tree-label').click();
await page.getByRole('tab', { name: /Карточки/ }).click();
await page.getByRole('button', { name: 'Карточка' }).click();
await page.waitForTimeout(400);
await page.screenshot({ path: OUT + '/m7-modal.png' });
const overflow = await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth || [...document.querySelectorAll('.main *')].some((e) => e.getBoundingClientRect().right > window.innerWidth + 2 && getComputedStyle(e).position !== 'fixed'));
console.log('horizontal overflow:', overflow, 'errors', JSON.stringify(errors));
await browser.close();
