import { chromium } from 'playwright';
import fs from 'fs';
const OUT = 'out16m'; fs.mkdirSync(OUT, { recursive: true });
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' });
const p = await b.newPage({ viewport: { width: 380, height: 800 }, isMobile: true, hasTouch: true });
const errors = []; p.on('pageerror', (e) => errors.push(e.message));
await p.goto('http://localhost:4174');
await p.getByRole('button', { name: 'Пропустить' }).click({ timeout: 2500 }).catch(() => {}); // знакомство при первом запуске
await p.getByRole('button', { name: 'Посмотреть на примере' }).click();
await p.waitForTimeout(400);
const menu = async () => { await p.locator('.mobile-bar button').first().click(); await p.waitForTimeout(300); };
await menu();
await p.locator('.tree-row.subject', { hasText: 'Физика' }).locator('.twisty').click();
await p.locator('.tree-row', { hasText: 'Закон Ома' }).locator('.tree-label').click();
await p.waitForTimeout(500);
await p.getByRole('button', { name: '+ Дата контрольной' }).click();
const ex = new Date(); ex.setDate(ex.getDate() + 5);
await p.locator('.topic-head input[type=date]').fill(ex.toISOString().slice(0, 10));
await p.locator('.title-input').click();
await p.waitForTimeout(400);
await p.screenshot({ path: OUT + '/1-topic.png' });
await p.locator('.mobile-brand').click();
await p.waitForTimeout(300);
await p.locator('.add-schedule').click();
await p.getByRole('button', { name: 'Заполнить расписание' }).click();
await p.locator('.sched-day').nth(0).locator('.sched-add').click();
await p.locator('.sched-menu button', { hasText: 'Физика' }).click();
await p.screenshot({ path: OUT + '/2-sched.png' });
await p.getByRole('button', { name: 'Готово' }).click();
await p.waitForTimeout(300);
await p.evaluate(() => document.querySelector('.exam-card')?.scrollIntoView());
await p.screenshot({ path: OUT + '/3-today.png' });
await menu();
await p.locator('.nav-item', { hasText: 'Домашка' }).click();
await p.waitForTimeout(300);
await p.screenshot({ path: OUT + '/4-hw.png' });
console.log('overflow', await p.evaluate(() => document.documentElement.scrollWidth - innerWidth), 'errors', JSON.stringify(errors));
await b.close();
