import { chromium } from 'playwright';
import fs from 'fs';
const OUT = 'out163'; fs.mkdirSync(OUT, { recursive: true });
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' });
const p = await b.newPage({ viewport: { width: 380, height: 780 }, isMobile: true, hasTouch: true });
const errors = []; p.on('pageerror', (e) => errors.push(e.message));
await p.goto('http://localhost:4174');
await p.getByRole('button', { name: 'Пропустить' }).click({ timeout: 2500 }).catch(() => {}); // знакомство при первом запуске
await p.getByRole('button', { name: 'Посмотреть на примере' }).click();
await p.waitForTimeout(500);
await p.locator('.foot-btn[aria-label="Возможности"]').click().catch(() => {});
const menu = p.locator('.mob-menu, .sidebar').first();
const openMenu = async () => { await p.locator('button.tab:has-text("Знания")').first().click(); await p.waitForTimeout(300); };
await openMenu();
await p.locator('.tree-row.subject', { hasText: 'Биология' }).locator('.tree-label').click();
await p.waitForTimeout(500);
await p.locator('.tabs-narrow button, .tabs-narrow [role=radio]', { hasText: 'Термины' }).click();
await p.waitForTimeout(300);
await p.getByRole('button', { name: 'Записать общие термины' }).click();
await p.waitForTimeout(300);
await p.locator('.new-row textarea').nth(0).fill('Гидрофобность');
await p.locator('.new-row textarea').nth(0).press('Enter');
await p.locator('.new-row textarea').nth(1).fill('Свойство молекул отталкивать воду');
await p.locator('.new-row textarea').nth(1).press('Enter');
await p.waitForTimeout(300);
await p.locator('.terms-chips .hw-fchip', { hasText: 'Все' }).click();
await p.waitForTimeout(400);
const ovf = await p.evaluate(() => document.documentElement.scrollWidth > innerWidth + 1);
console.log('terms overflow', ovf);
await p.screenshot({ path: OUT + '/m-terms.png' });
// конспект: выделение на телефоне → панель сама
await openMenu();
await p.locator('.tree-row.subject', { hasText: 'Физика' }).locator('.twisty').click();
await p.locator('.tree-row', { hasText: 'Закон Ома' }).locator('.tree-label').click();
await p.waitForTimeout(800);
await p.locator('.ProseMirror').focus();
await p.evaluate(() => { const n = [...document.querySelectorAll('.ProseMirror p')][0].lastChild; const r = document.createRange(); r.setStart(n, 5); r.setEnd(n, 20); getSelection().removeAllRanges(); getSelection().addRange(r); });
await p.waitForTimeout(700);
console.log('mobile bubble:', await p.evaluate(() => { const b = document.querySelector('.bubble'); return !!b && getComputedStyle(b).visibility !== 'hidden'; }));
console.log('errors', JSON.stringify(errors));
await b.close();
