import { chromium } from 'playwright';
const OUT = process.env.OUT;
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' });
const page = await browser.newPage({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2, isMobile: true, hasTouch: true });
const errors = [];
page.on('pageerror', (e) => errors.push(e.message));
await page.goto('http://localhost:4174');
await page.getByRole('button', { name: 'Пропустить' }).click({ timeout: 2500 }).catch(() => {}); // знакомство при первом запуске
await page.getByRole('button', { name: 'Посмотреть на примере' }).click();
await page.getByRole('button', { name: 'Знания' }).click();
await page.locator('.tree-row.subject', { hasText: 'Физика' }).locator('.twisty').click();
await page.locator('.tree-row', { hasText: 'Закон Ома' }).locator('.tree-label').click();
await page.waitForTimeout(400);
await page.getByRole('button', { name: 'Добавить словарь или список' }).click();
await page.waitForTimeout(300);
await page.screenshot({ path: OUT + '/m-plus.png' });
await page.getByRole('menuitem', { name: /Термины/ }).click();
await page.getByRole('button', { name: 'Вставить списком' }).click();
await page.locator('.paste-area').fill('Сила тока — заряд, проходящий через проводник за 1 с\nНапряжение — работа поля по переносу заряда 1 Кл\nСопротивление: свойство проводника препятствовать току');
await page.getByRole('button', { name: /^Добавить 3/ }).click();
await page.waitForTimeout(500);
await page.screenshot({ path: OUT + '/m-list.png' });
await page.getByRole('button', { name: 'Знания' }).click();
await page.locator('.tree-row.subject', { hasText: 'Физика' }).locator('.tree-label').click();
await page.getByRole('radio', { name: /Правила/ }).click();
await page.waitForTimeout(300);
await page.screenshot({ path: OUT + '/m-rules.png' });
const overflow = await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth);
console.log('overflow', overflow, 'errors', JSON.stringify(errors));
await browser.close();
