import { chromium } from 'playwright';
const OUT = process.env.OUT;
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' });
const p = await b.newPage({ viewport: { width: 390, height: 800 }, deviceScaleFactor: 2, isMobile: true, hasTouch: true });
const errors = [];
p.on('pageerror', (e) => errors.push(e.message));
await p.goto('http://localhost:4174');
await p.getByRole('button', { name: 'Пропустить' }).click({ timeout: 2500 }).catch(() => {}); // знакомство при первом запуске
await p.getByRole('button', { name: 'Посмотреть на примере' }).click();
await p.waitForTimeout(500);
await p.locator('.hw-today').getByRole('button', { name: /Записать/ }).click();
await p.waitForTimeout(400);
await p.screenshot({ path: OUT + '/k1-hwform.png' });
await p.locator('.modal .hw-text').fill('Выучить стих');
await p.locator('.modal').getByRole('button', { name: 'Записать' }).click();
await p.waitForTimeout(400);
await p.screenshot({ path: OUT + '/k2-today.png' });
await p.locator('.mobile-bar button[aria-label="Поиск"]').click();
await p.locator('.palette input').fill('клетк');
await p.waitForTimeout(300);
await p.screenshot({ path: OUT + '/k3-search.png' });
await p.keyboard.press('Escape');
await p.locator('.mobile-bar button').first().click();
await p.waitForTimeout(400);
await p.screenshot({ path: OUT + '/k4-drawer.png' });
console.log('overflow', await p.evaluate(() => document.documentElement.scrollWidth - innerWidth), 'errors', JSON.stringify(errors));
await b.close();
