import { _electron as electron } from 'playwright';
import fs from 'fs';
const OUT = process.env.OUT;
fs.rmSync('/tmp/mnemaS', { recursive: true, force: true });
const app = await electron.launch({ executablePath: process.cwd() + '/node_modules/electron/dist/electron', args: [process.cwd() + '', '--no-sandbox'], env: { ...process.env, MNEMA_USER_DATA: '/tmp/mnemaS' } });
const win = await app.firstWindow();
const errors = []; win.on('pageerror', (e) => errors.push(e.message));
await win.getByRole('button', { name: 'Посмотреть на примере' }).click();
await win.getByRole('button', { name: /Добавить расписание/ }).click();
await win.getByRole('button', { name: 'Заполнить' }).click();
const lessons = win.locator('.lesson.toggle');
const n = await lessons.count();
for (let i = 0; i < n; i += 2) await lessons.nth(i).click();
await win.getByRole('button', { name: 'Готово' }).click();
await win.waitForTimeout(600);
await win.locator('.schedule-card').scrollIntoViewIfNeeded();
await win.locator('.schedule-card').screenshot({ path: OUT + '/sched.png' });
await win.setViewportSize?.({ width: 900, height: 800 });
console.log('errors', JSON.stringify(errors));
await app.close();
